### PR TITLE
do not set discard if max-age set

### PR DESCRIPTION
**Pull request by robnagler**

### CODE REVIEW

**Comment by oalders** [comment]
Thanks @robnagler! Would you be able to add an appropriate test for this?

**Comment by robnagler** [comment]
@oalders I tested the fix against [our test](https://github.com/biviosoftware/perl-Bivio/blob/master/Ext/t/HTTPCookies.bunit). We [wrap HTTP::Cookies](https://github.com/biviosoftware/perl-Bivio/blob/master/Ext/HTTPCookies.pm) so we could push out fixes independently. I'm fine if you don't merge this. I just wanted to let you know that there is a problem and how to fix it.

**Comment by oalders** [comment]
@robnagler understood.  I appreciate the contribution. 👍

**Comment by oalders** [comment]
@robnagler do you mind if we keep this issue open?

**Comment by robnagler** [comment]
I thought it was not wanted. It's been 6 months. It's your call. I was just cleaning up my pulls.

**Comment by oalders** [comment]
The wheels are just turning slowly. ;) The change just needs an accompanying test that I'm hoping someone will contribute. We are understaffed over here. It's not a reflection on the PR.

**Pull request closed without merging**
