### PR TITLE
tests for #61 - do not set discard if max-age is set

### PR DESCRIPTION
**Pull request by simbabque**
Original change by @robnagler. I've also fixed a random typo in a test description.

Closes #61

### CODE REVIEW

**Review by oalders — APPROVED** [review]
Thanks @simbabque!

**Comment by simbabque** [comment]
Looks like I am really bad at counting. Not sure what's going on there, I had 80 and it was green when I ran it locally. Investigating.

**Comment by simbabque** [comment]
Let's hold this until #66 was merged. I will then rebase and force-push.

**Comment by oalders** [comment]
Ok to rebase now. :)

**Review by oalders — APPROVED** [review]
👍

**Comment by oalders** [comment]
Thanks @simbabque!

**Pull request merged**
