### PR TITLE
Netscape: allow HttpOnly cookies to be loaded

### LINKED ISSUE #63: HTTP::Cookies::Netscape discards HttpOnly cookies as written by curl
curl generates cookie jars where HttpOnly cookies have hostnames prepended with `#HttpOnly_` (https://curl.se/libcurl/c/CURLOPT_COOKIELIST.html). For example, curl is capable of generating a file like this:

```
# Netscape HTTP Cookie File
# http://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_www.acme.com    FALSE   /       FALSE   2147483647      foo1    bar
```

The file above represents a HttpOnly cookie with a hostname of `www.acme.com`. `HTTP::Cookies::Netscape` discards the above as a comment. It would be helpful if HttpOnly cookies could be loaded in.

https://www.perlmonks.org/?node_id=1187917 is a PerlMonks thread where somebody else hit this case in April 2017.

### PR DESCRIPTION
**Pull request by chigley**
Fixes #63, which contains all of the details.

### CODE REVIEW

**Review by oalders — APPROVED** [review]
👍

**Comment by oalders** [comment]
Thanks @chigley!

**Comment by chigley** [comment]
Thanks @oalders  for merging! :smile:

**Comment by oalders** [comment]
You're welcome, @chigley! I also uploaded a new release a few days ago.

**Pull request merged**
