### PR TITLE
Whenever possible, use an absolute four digit year for Time::Local

### PR DESCRIPTION
**Pull request by oalders**
Apply patch from https://rt.cpan.org/Public/Bug/Display.html?id=124527

### CODE REVIEW

**Comment by oalders** [comment]
@genio ping

**Comment by karenetheridge** [comment]
As discussed on irc, since MacOS Classic is not an architecture anyone uses any longer (so far as we know), it is also an option to do nothing (close this PR), or drop support for that architecture entirely.

**Comment by genio** [comment]
While I don't think there's any reason to keep this around further, I agree that using a four-digit year is good practice. If we leave the block in place, let's at least do that much. Can you alter the PR to not change the function used so we don't worry about that and simply alter the two-digit year to be a four-digit year?

**Comment by oalders** [comment]
I think my preference at this point is just to remove that block of code.  Does that work for you?

**Comment by genio** [comment]
Dropping support for the architecture sounds good (block removal).

**Pull request merged**
